version: '3.8'

services:
  web:
    build: .
    command: gunicorn medicos.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  marytts:
    image: synesthesiam/marytts:5.2
    ports:
      - "59125:59125"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:59125"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  redis_data:
  postgres_data:
  static_volume: